name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - name: merge Bluetooth disconnect PR 1638
        shell: bash
        run: |
          cd src
          git remote add upstream https://github.com/zmkfirmware/zmk.git
          git fetch upstream pull/1638/head:refs/remotes/upstream/pull/1638
          git merge -c "Merge PR#1638" refs/remotes/upstream/pull/1638
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v10
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80.uf2
          path: glove80.uf2
